name: Build And Deploy

on: workflow_dispatch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Build and Deploy
        id: deploy
        uses: withastro/action@configure-site
        # when this is released, it will be withastro/action@v2